// Code generated by ogen, DO NOT EDIT.

package opencodeapi

import (
	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/uri"
)

// EncodeURI encodes V2AgentListLocation as URI form.
func (s *V2AgentListLocation) EncodeURI(e uri.Encoder) error {
	if err := e.EncodeField("directory", func(e uri.Encoder) error {
		if val, ok := s.Directory.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"directory\"")
	}
	if err := e.EncodeField("workspace", func(e uri.Encoder) error {
		if val, ok := s.Workspace.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"workspace\"")
	}
	return nil
}

var uriFieldsNameOfV2AgentListLocation = [2]string{
	0: "directory",
	1: "workspace",
}

// DecodeURI decodes V2AgentListLocation from URI form.
func (s *V2AgentListLocation) DecodeURI(d uri.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode V2AgentListLocation to nil")
	}

	if err := d.DecodeFields(func(k string, d uri.Decoder) error {
		switch k {
		case "directory":
			if err := func() error {
				var sDotDirectoryVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotDirectoryVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Directory.SetTo(sDotDirectoryVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"directory\"")
			}
		case "workspace":
			if err := func() error {
				var sDotWorkspaceVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotWorkspaceVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Workspace.SetTo(sDotWorkspaceVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"workspace\"")
			}
		default:
			return errors.Errorf("unexpected field %q", k)
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode V2AgentListLocation")
	}

	return nil
}

// EncodeURI encodes V2ModelListLocation as URI form.
func (s *V2ModelListLocation) EncodeURI(e uri.Encoder) error {
	if err := e.EncodeField("directory", func(e uri.Encoder) error {
		if val, ok := s.Directory.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"directory\"")
	}
	if err := e.EncodeField("workspace", func(e uri.Encoder) error {
		if val, ok := s.Workspace.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"workspace\"")
	}
	return nil
}

var uriFieldsNameOfV2ModelListLocation = [2]string{
	0: "directory",
	1: "workspace",
}

// DecodeURI decodes V2ModelListLocation from URI form.
func (s *V2ModelListLocation) DecodeURI(d uri.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode V2ModelListLocation to nil")
	}

	if err := d.DecodeFields(func(k string, d uri.Decoder) error {
		switch k {
		case "directory":
			if err := func() error {
				var sDotDirectoryVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotDirectoryVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Directory.SetTo(sDotDirectoryVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"directory\"")
			}
		case "workspace":
			if err := func() error {
				var sDotWorkspaceVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotWorkspaceVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Workspace.SetTo(sDotWorkspaceVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"workspace\"")
			}
		default:
			return errors.Errorf("unexpected field %q", k)
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode V2ModelListLocation")
	}

	return nil
}

// EncodeURI encodes V2PermissionRequestListLocation as URI form.
func (s *V2PermissionRequestListLocation) EncodeURI(e uri.Encoder) error {
	if err := e.EncodeField("directory", func(e uri.Encoder) error {
		if val, ok := s.Directory.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"directory\"")
	}
	if err := e.EncodeField("workspace", func(e uri.Encoder) error {
		if val, ok := s.Workspace.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"workspace\"")
	}
	return nil
}

var uriFieldsNameOfV2PermissionRequestListLocation = [2]string{
	0: "directory",
	1: "workspace",
}

// DecodeURI decodes V2PermissionRequestListLocation from URI form.
func (s *V2PermissionRequestListLocation) DecodeURI(d uri.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode V2PermissionRequestListLocation to nil")
	}

	if err := d.DecodeFields(func(k string, d uri.Decoder) error {
		switch k {
		case "directory":
			if err := func() error {
				var sDotDirectoryVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotDirectoryVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Directory.SetTo(sDotDirectoryVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"directory\"")
			}
		case "workspace":
			if err := func() error {
				var sDotWorkspaceVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotWorkspaceVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Workspace.SetTo(sDotWorkspaceVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"workspace\"")
			}
		default:
			return errors.Errorf("unexpected field %q", k)
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode V2PermissionRequestListLocation")
	}

	return nil
}

// EncodeURI encodes V2ProviderListLocation as URI form.
func (s *V2ProviderListLocation) EncodeURI(e uri.Encoder) error {
	if err := e.EncodeField("directory", func(e uri.Encoder) error {
		if val, ok := s.Directory.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"directory\"")
	}
	if err := e.EncodeField("workspace", func(e uri.Encoder) error {
		if val, ok := s.Workspace.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"workspace\"")
	}
	return nil
}

var uriFieldsNameOfV2ProviderListLocation = [2]string{
	0: "directory",
	1: "workspace",
}

// DecodeURI decodes V2ProviderListLocation from URI form.
func (s *V2ProviderListLocation) DecodeURI(d uri.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode V2ProviderListLocation to nil")
	}

	if err := d.DecodeFields(func(k string, d uri.Decoder) error {
		switch k {
		case "directory":
			if err := func() error {
				var sDotDirectoryVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotDirectoryVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Directory.SetTo(sDotDirectoryVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"directory\"")
			}
		case "workspace":
			if err := func() error {
				var sDotWorkspaceVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotWorkspaceVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Workspace.SetTo(sDotWorkspaceVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"workspace\"")
			}
		default:
			return errors.Errorf("unexpected field %q", k)
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode V2ProviderListLocation")
	}

	return nil
}

// EncodeURI encodes V2QuestionRequestListLocation as URI form.
func (s *V2QuestionRequestListLocation) EncodeURI(e uri.Encoder) error {
	if err := e.EncodeField("directory", func(e uri.Encoder) error {
		if val, ok := s.Directory.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"directory\"")
	}
	if err := e.EncodeField("workspace", func(e uri.Encoder) error {
		if val, ok := s.Workspace.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"workspace\"")
	}
	return nil
}

var uriFieldsNameOfV2QuestionRequestListLocation = [2]string{
	0: "directory",
	1: "workspace",
}

// DecodeURI decodes V2QuestionRequestListLocation from URI form.
func (s *V2QuestionRequestListLocation) DecodeURI(d uri.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode V2QuestionRequestListLocation to nil")
	}

	if err := d.DecodeFields(func(k string, d uri.Decoder) error {
		switch k {
		case "directory":
			if err := func() error {
				var sDotDirectoryVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotDirectoryVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Directory.SetTo(sDotDirectoryVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"directory\"")
			}
		case "workspace":
			if err := func() error {
				var sDotWorkspaceVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotWorkspaceVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Workspace.SetTo(sDotWorkspaceVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"workspace\"")
			}
		default:
			return errors.Errorf("unexpected field %q", k)
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode V2QuestionRequestListLocation")
	}

	return nil
}
