// Code generated by ogen, DO NOT EDIT.

package opencodeapi

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// SessionCreateParams is parameters of session.create operation.
type SessionCreateParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

func unpackSessionCreateParams(packed middleware.Parameters) (params SessionCreateParams) {
	{
		key := middleware.ParameterKey{
			Name: "directory",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Directory = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "workspace",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Workspace = v.(OptString)
		}
	}
	return params
}

func decodeSessionCreateParams(args [0]string, argsEscaped bool, r *http.Request) (params SessionCreateParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: directory.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "directory",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotDirectoryVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotDirectoryVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Directory.SetTo(paramsDotDirectoryVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "directory",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: workspace.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "workspace",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotWorkspaceVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotWorkspaceVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Workspace.SetTo(paramsDotWorkspaceVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "workspace",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// SessionMessageParams is parameters of session.message operation.
type SessionMessageParams struct {
	SessionID string
	Directory OptString `json:",omitempty,omitzero"`
}

func unpackSessionMessageParams(packed middleware.Parameters) (params SessionMessageParams) {
	{
		key := middleware.ParameterKey{
			Name: "sessionID",
			In:   "path",
		}
		params.SessionID = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "directory",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Directory = v.(OptString)
		}
	}
	return params
}

func decodeSessionMessageParams(args [1]string, argsEscaped bool, r *http.Request) (params SessionMessageParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode path: sessionID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "sessionID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.SessionID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "sessionID",
			In:   "path",
			Err:  err,
		}
	}
	// Decode query: directory.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "directory",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotDirectoryVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotDirectoryVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Directory.SetTo(paramsDotDirectoryVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "directory",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// SessionMessagesParams is parameters of session.messages operation.
type SessionMessagesParams struct {
	SessionID string
	Directory OptString `json:",omitempty,omitzero"`
	Before    OptString `json:",omitempty,omitzero"`
	Limit     OptInt    `json:",omitempty,omitzero"`
}

func unpackSessionMessagesParams(packed middleware.Parameters) (params SessionMessagesParams) {
	{
		key := middleware.ParameterKey{
			Name: "sessionID",
			In:   "path",
		}
		params.SessionID = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "directory",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Directory = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "before",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Before = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "limit",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Limit = v.(OptInt)
		}
	}
	return params
}

func decodeSessionMessagesParams(args [1]string, argsEscaped bool, r *http.Request) (params SessionMessagesParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode path: sessionID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "sessionID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.SessionID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "sessionID",
			In:   "path",
			Err:  err,
		}
	}
	// Decode query: directory.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "directory",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotDirectoryVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotDirectoryVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Directory.SetTo(paramsDotDirectoryVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "directory",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: before.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "before",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotBeforeVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotBeforeVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Before.SetTo(paramsDotBeforeVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "before",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: limit.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotLimitVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotLimitVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Limit.SetTo(paramsDotLimitVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Limit.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        true,
							Min:           0,
							MaxSet:        false,
							Max:           0,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "limit",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// V2AgentListParams is parameters of v2.agent.list operation.
type V2AgentListParams struct {
	Location OptV2AgentListLocation `json:",omitempty,omitzero"`
}

func unpackV2AgentListParams(packed middleware.Parameters) (params V2AgentListParams) {
	{
		key := middleware.ParameterKey{
			Name: "location",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Location = v.(OptV2AgentListLocation)
		}
	}
	return params
}

func decodeV2AgentListParams(args [0]string, argsEscaped bool, r *http.Request) (params V2AgentListParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: location.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "location",
			Style:   uri.QueryStyleDeepObject,
			Explode: true,
			Fields:  []uri.QueryParameterObjectField{{Name: "directory", Required: false}, {Name: "workspace", Required: false}},
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotLocationVal V2AgentListLocation
				if err := func() error {
					return paramsDotLocationVal.DecodeURI(d)
				}(); err != nil {
					return err
				}
				params.Location.SetTo(paramsDotLocationVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "location",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// V2ModelListParams is parameters of v2.model.list operation.
type V2ModelListParams struct {
	Location OptV2ModelListLocation `json:",omitempty,omitzero"`
}

func unpackV2ModelListParams(packed middleware.Parameters) (params V2ModelListParams) {
	{
		key := middleware.ParameterKey{
			Name: "location",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Location = v.(OptV2ModelListLocation)
		}
	}
	return params
}

func decodeV2ModelListParams(args [0]string, argsEscaped bool, r *http.Request) (params V2ModelListParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: location.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "location",
			Style:   uri.QueryStyleDeepObject,
			Explode: true,
			Fields:  []uri.QueryParameterObjectField{{Name: "directory", Required: false}, {Name: "workspace", Required: false}},
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotLocationVal V2ModelListLocation
				if err := func() error {
					return paramsDotLocationVal.DecodeURI(d)
				}(); err != nil {
					return err
				}
				params.Location.SetTo(paramsDotLocationVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "location",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// V2PermissionRequestListParams is parameters of v2.permission.request.list operation.
type V2PermissionRequestListParams struct {
	Location OptV2PermissionRequestListLocation `json:",omitempty,omitzero"`
}

func unpackV2PermissionRequestListParams(packed middleware.Parameters) (params V2PermissionRequestListParams) {
	{
		key := middleware.ParameterKey{
			Name: "location",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Location = v.(OptV2PermissionRequestListLocation)
		}
	}
	return params
}

func decodeV2PermissionRequestListParams(args [0]string, argsEscaped bool, r *http.Request) (params V2PermissionRequestListParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: location.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "location",
			Style:   uri.QueryStyleDeepObject,
			Explode: true,
			Fields:  []uri.QueryParameterObjectField{{Name: "directory", Required: false}, {Name: "workspace", Required: false}},
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotLocationVal V2PermissionRequestListLocation
				if err := func() error {
					return paramsDotLocationVal.DecodeURI(d)
				}(); err != nil {
					return err
				}
				params.Location.SetTo(paramsDotLocationVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "location",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// V2ProviderListParams is parameters of v2.provider.list operation.
type V2ProviderListParams struct {
	Location OptV2ProviderListLocation `json:",omitempty,omitzero"`
}

func unpackV2ProviderListParams(packed middleware.Parameters) (params V2ProviderListParams) {
	{
		key := middleware.ParameterKey{
			Name: "location",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Location = v.(OptV2ProviderListLocation)
		}
	}
	return params
}

func decodeV2ProviderListParams(args [0]string, argsEscaped bool, r *http.Request) (params V2ProviderListParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: location.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "location",
			Style:   uri.QueryStyleDeepObject,
			Explode: true,
			Fields:  []uri.QueryParameterObjectField{{Name: "directory", Required: false}, {Name: "workspace", Required: false}},
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotLocationVal V2ProviderListLocation
				if err := func() error {
					return paramsDotLocationVal.DecodeURI(d)
				}(); err != nil {
					return err
				}
				params.Location.SetTo(paramsDotLocationVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "location",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// V2QuestionRequestListParams is parameters of v2.question.request.list operation.
type V2QuestionRequestListParams struct {
	Location OptV2QuestionRequestListLocation `json:",omitempty,omitzero"`
}

func unpackV2QuestionRequestListParams(packed middleware.Parameters) (params V2QuestionRequestListParams) {
	{
		key := middleware.ParameterKey{
			Name: "location",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Location = v.(OptV2QuestionRequestListLocation)
		}
	}
	return params
}

func decodeV2QuestionRequestListParams(args [0]string, argsEscaped bool, r *http.Request) (params V2QuestionRequestListParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: location.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "location",
			Style:   uri.QueryStyleDeepObject,
			Explode: true,
			Fields:  []uri.QueryParameterObjectField{{Name: "directory", Required: false}, {Name: "workspace", Required: false}},
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotLocationVal V2QuestionRequestListLocation
				if err := func() error {
					return paramsDotLocationVal.DecodeURI(d)
				}(); err != nil {
					return err
				}
				params.Location.SetTo(paramsDotLocationVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "location",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// V2SessionContextParams is parameters of v2.session.context operation.
type V2SessionContextParams struct {
	SessionID string
}

func unpackV2SessionContextParams(packed middleware.Parameters) (params V2SessionContextParams) {
	{
		key := middleware.ParameterKey{
			Name: "sessionID",
			In:   "path",
		}
		params.SessionID = packed[key].(string)
	}
	return params
}

func decodeV2SessionContextParams(args [1]string, argsEscaped bool, r *http.Request) (params V2SessionContextParams, _ error) {
	// Decode path: sessionID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "sessionID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.SessionID = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     0,
					MaxLengthSet:  false,
					Email:         false,
					Hostname:      false,
					Regex:         regexMap["^ses"],
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.SessionID)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "sessionID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// V2SessionListParams is parameters of v2.session.list operation.
type V2SessionListParams struct {
	Workspace OptString             `json:",omitempty,omitzero"`
	Limit     OptFloat64            `json:",omitempty,omitzero"`
	Order     OptV2SessionListOrder `json:",omitempty,omitzero"`
	Search    OptString             `json:",omitempty,omitzero"`
	Directory OptString             `json:",omitempty,omitzero"`
	Project   OptString             `json:",omitempty,omitzero"`
	Subpath   OptString             `json:",omitempty,omitzero"`
	Cursor    OptString             `json:",omitempty,omitzero"`
}

func unpackV2SessionListParams(packed middleware.Parameters) (params V2SessionListParams) {
	{
		key := middleware.ParameterKey{
			Name: "workspace",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Workspace = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "limit",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Limit = v.(OptFloat64)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "order",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Order = v.(OptV2SessionListOrder)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "search",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Search = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "directory",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Directory = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "project",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Project = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "subpath",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Subpath = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "cursor",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Cursor = v.(OptString)
		}
	}
	return params
}

func decodeV2SessionListParams(args [0]string, argsEscaped bool, r *http.Request) (params V2SessionListParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: workspace.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "workspace",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotWorkspaceVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotWorkspaceVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Workspace.SetTo(paramsDotWorkspaceVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Workspace.Get(); ok {
					if err := func() error {
						if err := (validate.String{
							MinLength:     0,
							MinLengthSet:  false,
							MaxLength:     0,
							MaxLengthSet:  false,
							Email:         false,
							Hostname:      false,
							Regex:         regexMap["^wrk"],
							MinNumeric:    0,
							MinNumericSet: false,
							MaxNumeric:    0,
							MaxNumericSet: false,
						}).Validate(string(value)); err != nil {
							return errors.Wrap(err, "string")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "workspace",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: limit.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotLimitVal float64
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToFloat64(val)
					if err != nil {
						return err
					}

					paramsDotLimitVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Limit.SetTo(paramsDotLimitVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Limit.Get(); ok {
					if err := func() error {
						if err := (validate.Float{}).Validate(float64(value)); err != nil {
							return errors.Wrap(err, "float")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "limit",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: order.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "order",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotOrderVal V2SessionListOrder
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotOrderVal = V2SessionListOrder(c)
					return nil
				}(); err != nil {
					return err
				}
				params.Order.SetTo(paramsDotOrderVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Order.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "order",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: search.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "search",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotSearchVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotSearchVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Search.SetTo(paramsDotSearchVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "search",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: directory.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "directory",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotDirectoryVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotDirectoryVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Directory.SetTo(paramsDotDirectoryVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "directory",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: project.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "project",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotProjectVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotProjectVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Project.SetTo(paramsDotProjectVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "project",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: subpath.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "subpath",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotSubpathVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotSubpathVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Subpath.SetTo(paramsDotSubpathVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "subpath",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: cursor.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "cursor",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotCursorVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotCursorVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Cursor.SetTo(paramsDotCursorVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "cursor",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// V2SessionMessagesParams is parameters of v2.session.messages operation.
type V2SessionMessagesParams struct {
	SessionID string
	Limit     OptFloat64                `json:",omitempty,omitzero"`
	Order     OptV2SessionMessagesOrder `json:",omitempty,omitzero"`
	Cursor    OptString                 `json:",omitempty,omitzero"`
}

func unpackV2SessionMessagesParams(packed middleware.Parameters) (params V2SessionMessagesParams) {
	{
		key := middleware.ParameterKey{
			Name: "sessionID",
			In:   "path",
		}
		params.SessionID = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "limit",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Limit = v.(OptFloat64)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "order",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Order = v.(OptV2SessionMessagesOrder)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "cursor",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Cursor = v.(OptString)
		}
	}
	return params
}

func decodeV2SessionMessagesParams(args [1]string, argsEscaped bool, r *http.Request) (params V2SessionMessagesParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode path: sessionID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "sessionID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.SessionID = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     0,
					MaxLengthSet:  false,
					Email:         false,
					Hostname:      false,
					Regex:         regexMap["^ses"],
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.SessionID)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "sessionID",
			In:   "path",
			Err:  err,
		}
	}
	// Decode query: limit.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotLimitVal float64
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToFloat64(val)
					if err != nil {
						return err
					}

					paramsDotLimitVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Limit.SetTo(paramsDotLimitVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Limit.Get(); ok {
					if err := func() error {
						if err := (validate.Float{}).Validate(float64(value)); err != nil {
							return errors.Wrap(err, "float")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "limit",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: order.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "order",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotOrderVal V2SessionMessagesOrder
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotOrderVal = V2SessionMessagesOrder(c)
					return nil
				}(); err != nil {
					return err
				}
				params.Order.SetTo(paramsDotOrderVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Order.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "order",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: cursor.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "cursor",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotCursorVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotCursorVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Cursor.SetTo(paramsDotCursorVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "cursor",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// V2SessionPermissionListParams is parameters of v2.session.permission.list operation.
type V2SessionPermissionListParams struct {
	SessionID string
}

func unpackV2SessionPermissionListParams(packed middleware.Parameters) (params V2SessionPermissionListParams) {
	{
		key := middleware.ParameterKey{
			Name: "sessionID",
			In:   "path",
		}
		params.SessionID = packed[key].(string)
	}
	return params
}

func decodeV2SessionPermissionListParams(args [1]string, argsEscaped bool, r *http.Request) (params V2SessionPermissionListParams, _ error) {
	// Decode path: sessionID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "sessionID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.SessionID = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     0,
					MaxLengthSet:  false,
					Email:         false,
					Hostname:      false,
					Regex:         regexMap["^ses"],
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.SessionID)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "sessionID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// V2SessionPermissionReplyParams is parameters of v2.session.permission.reply operation.
type V2SessionPermissionReplyParams struct {
	SessionID string
	RequestID string
}

func unpackV2SessionPermissionReplyParams(packed middleware.Parameters) (params V2SessionPermissionReplyParams) {
	{
		key := middleware.ParameterKey{
			Name: "sessionID",
			In:   "path",
		}
		params.SessionID = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "requestID",
			In:   "path",
		}
		params.RequestID = packed[key].(string)
	}
	return params
}

func decodeV2SessionPermissionReplyParams(args [2]string, argsEscaped bool, r *http.Request) (params V2SessionPermissionReplyParams, _ error) {
	// Decode path: sessionID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "sessionID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.SessionID = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     0,
					MaxLengthSet:  false,
					Email:         false,
					Hostname:      false,
					Regex:         regexMap["^ses"],
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.SessionID)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "sessionID",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: requestID.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "requestID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.RequestID = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     0,
					MaxLengthSet:  false,
					Email:         false,
					Hostname:      false,
					Regex:         regexMap["^per"],
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.RequestID)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "requestID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// V2SessionPromptParams is parameters of v2.session.prompt operation.
type V2SessionPromptParams struct {
	SessionID string
}

func unpackV2SessionPromptParams(packed middleware.Parameters) (params V2SessionPromptParams) {
	{
		key := middleware.ParameterKey{
			Name: "sessionID",
			In:   "path",
		}
		params.SessionID = packed[key].(string)
	}
	return params
}

func decodeV2SessionPromptParams(args [1]string, argsEscaped bool, r *http.Request) (params V2SessionPromptParams, _ error) {
	// Decode path: sessionID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "sessionID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.SessionID = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     0,
					MaxLengthSet:  false,
					Email:         false,
					Hostname:      false,
					Regex:         regexMap["^ses"],
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.SessionID)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "sessionID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// V2SessionQuestionRejectParams is parameters of v2.session.question.reject operation.
type V2SessionQuestionRejectParams struct {
	SessionID string
	RequestID string
}

func unpackV2SessionQuestionRejectParams(packed middleware.Parameters) (params V2SessionQuestionRejectParams) {
	{
		key := middleware.ParameterKey{
			Name: "sessionID",
			In:   "path",
		}
		params.SessionID = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "requestID",
			In:   "path",
		}
		params.RequestID = packed[key].(string)
	}
	return params
}

func decodeV2SessionQuestionRejectParams(args [2]string, argsEscaped bool, r *http.Request) (params V2SessionQuestionRejectParams, _ error) {
	// Decode path: sessionID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "sessionID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.SessionID = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     0,
					MaxLengthSet:  false,
					Email:         false,
					Hostname:      false,
					Regex:         regexMap["^ses"],
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.SessionID)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "sessionID",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: requestID.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "requestID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.RequestID = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     0,
					MaxLengthSet:  false,
					Email:         false,
					Hostname:      false,
					Regex:         regexMap["^que"],
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.RequestID)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "requestID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// V2SessionQuestionReplyParams is parameters of v2.session.question.reply operation.
type V2SessionQuestionReplyParams struct {
	SessionID string
	RequestID string
}

func unpackV2SessionQuestionReplyParams(packed middleware.Parameters) (params V2SessionQuestionReplyParams) {
	{
		key := middleware.ParameterKey{
			Name: "sessionID",
			In:   "path",
		}
		params.SessionID = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "requestID",
			In:   "path",
		}
		params.RequestID = packed[key].(string)
	}
	return params
}

func decodeV2SessionQuestionReplyParams(args [2]string, argsEscaped bool, r *http.Request) (params V2SessionQuestionReplyParams, _ error) {
	// Decode path: sessionID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "sessionID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.SessionID = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     0,
					MaxLengthSet:  false,
					Email:         false,
					Hostname:      false,
					Regex:         regexMap["^ses"],
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.SessionID)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "sessionID",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: requestID.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "requestID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.RequestID = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     0,
					MaxLengthSet:  false,
					Email:         false,
					Hostname:      false,
					Regex:         regexMap["^que"],
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.RequestID)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "requestID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// V2SessionWaitParams is parameters of v2.session.wait operation.
type V2SessionWaitParams struct {
	SessionID string
}

func unpackV2SessionWaitParams(packed middleware.Parameters) (params V2SessionWaitParams) {
	{
		key := middleware.ParameterKey{
			Name: "sessionID",
			In:   "path",
		}
		params.SessionID = packed[key].(string)
	}
	return params
}

func decodeV2SessionWaitParams(args [1]string, argsEscaped bool, r *http.Request) (params V2SessionWaitParams, _ error) {
	// Decode path: sessionID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "sessionID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.SessionID = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     0,
					MaxLengthSet:  false,
					Email:         false,
					Hostname:      false,
					Regex:         regexMap["^ses"],
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.SessionID)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "sessionID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
