// Code generated by ogen, DO NOT EDIT.
package opencodeapi

type SessionCreateRes interface {
	sessionCreateRes()
}

type SessionMessageRes interface {
	sessionMessageRes()
}

type SessionMessagesRes interface {
	sessionMessagesRes()
}

type V2AgentListRes interface {
	v2AgentListRes()
}

type V2HealthGetRes interface {
	v2HealthGetRes()
}

type V2ModelListRes interface {
	v2ModelListRes()
}

type V2PermissionRequestListRes interface {
	v2PermissionRequestListRes()
}

type V2ProviderListRes interface {
	v2ProviderListRes()
}

type V2QuestionRequestListRes interface {
	v2QuestionRequestListRes()
}

type V2SessionContextRes interface {
	v2SessionContextRes()
}

type V2SessionListRes interface {
	v2SessionListRes()
}

type V2SessionMessagesRes interface {
	v2SessionMessagesRes()
}

type V2SessionPermissionListRes interface {
	v2SessionPermissionListRes()
}

type V2SessionPermissionReplyRes interface {
	v2SessionPermissionReplyRes()
}

type V2SessionPromptRes interface {
	v2SessionPromptRes()
}

type V2SessionQuestionRejectRes interface {
	v2SessionQuestionRejectRes()
}

type V2SessionQuestionReplyRes interface {
	v2SessionQuestionReplyRes()
}

type V2SessionWaitRes interface {
	v2SessionWaitRes()
}
