// Code generated by ogen, DO NOT EDIT.

package opencodeapi

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/ogen-go/ogen/uri"
)

var (
	rn23AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn25AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn30AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn1AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn4AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
)

func (s *Server) cutPrefix(path string) (string, bool) {
	prefix := s.cfg.Prefix
	if prefix == "" {
		return path, true
	}
	if !strings.HasPrefix(path, prefix) {
		// Prefix doesn't match.
		return "", false
	}
	// Cut prefix from the path.
	return strings.TrimPrefix(path, prefix), true
}

// ServeHTTP serves http request as defined by OpenAPI v3 specification,
// calling handler that matches the path or returning not found error.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	elem := r.URL.Path
	elemIsEscaped := false
	if rawPath := r.URL.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
			elemIsEscaped = strings.ContainsRune(elem, '%')
		}
	}

	elem, ok := s.cutPrefix(elem)
	if !ok || len(elem) == 0 {
		s.notFound(w, r)
		return
	}
	args := [2]string{}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/"

			if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'a': // Prefix: "api/"

				if l := len("api/"); len(elem) >= l && elem[0:l] == "api/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'a': // Prefix: "agent"

					if l := len("agent"); len(elem) >= l && elem[0:l] == "agent" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleV2AgentListRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET",
								allowedHeaders: nil,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}

				case 'h': // Prefix: "health"

					if l := len("health"); len(elem) >= l && elem[0:l] == "health" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleV2HealthGetRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET",
								allowedHeaders: nil,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}

				case 'm': // Prefix: "model"

					if l := len("model"); len(elem) >= l && elem[0:l] == "model" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleV2ModelListRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET",
								allowedHeaders: nil,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}

				case 'p': // Prefix: "p"

					if l := len("p"); len(elem) >= l && elem[0:l] == "p" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'e': // Prefix: "ermission/request"

						if l := len("ermission/request"); len(elem) >= l && elem[0:l] == "ermission/request" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleV2PermissionRequestListRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: nil,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					case 'r': // Prefix: "rovider"

						if l := len("rovider"); len(elem) >= l && elem[0:l] == "rovider" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleV2ProviderListRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: nil,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					}

				case 'q': // Prefix: "question/request"

					if l := len("question/request"); len(elem) >= l && elem[0:l] == "question/request" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleV2QuestionRequestListRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET",
								allowedHeaders: nil,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}

				case 's': // Prefix: "session"

					if l := len("session"); len(elem) >= l && elem[0:l] == "session" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleV2SessionListRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET",
								allowedHeaders: nil,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "sessionID"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[0] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'c': // Prefix: "context"

								if l := len("context"); len(elem) >= l && elem[0:l] == "context" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "GET":
										s.handleV2SessionContextRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET",
											allowedHeaders: nil,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							case 'm': // Prefix: "message"

								if l := len("message"); len(elem) >= l && elem[0:l] == "message" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "GET":
										s.handleV2SessionMessagesRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET",
											allowedHeaders: nil,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							case 'p': // Prefix: "p"

								if l := len("p"); len(elem) >= l && elem[0:l] == "p" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'e': // Prefix: "ermission"

									if l := len("ermission"); len(elem) >= l && elem[0:l] == "ermission" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										switch r.Method {
										case "GET":
											s.handleV2SessionPermissionListRequest([1]string{
												args[0],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "GET",
												allowedHeaders: nil,
												acceptPost:     "",
												acceptPatch:    "",
											})
										}

										return
									}
									switch elem[0] {
									case '/': // Prefix: "/"

										if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
											elem = elem[l:]
										} else {
											break
										}

										// Param: "requestID"
										// Match until "/"
										idx := strings.IndexByte(elem, '/')
										if idx < 0 {
											idx = len(elem)
										}
										args[1] = elem[:idx]
										elem = elem[idx:]

										if len(elem) == 0 {
											break
										}
										switch elem[0] {
										case '/': // Prefix: "/reply"

											if l := len("/reply"); len(elem) >= l && elem[0:l] == "/reply" {
												elem = elem[l:]
											} else {
												break
											}

											if len(elem) == 0 {
												// Leaf node.
												switch r.Method {
												case "POST":
													s.handleV2SessionPermissionReplyRequest([2]string{
														args[0],
														args[1],
													}, elemIsEscaped, w, r)
												default:
													s.notAllowed(w, r, notAllowedParams{
														allowedMethods: "POST",
														allowedHeaders: rn23AllowedHeaders,
														acceptPost:     "application/json",
														acceptPatch:    "",
													})
												}

												return
											}

										}

									}

								case 'r': // Prefix: "rompt"

									if l := len("rompt"); len(elem) >= l && elem[0:l] == "rompt" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "POST":
											s.handleV2SessionPromptRequest([1]string{
												args[0],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "POST",
												allowedHeaders: rn25AllowedHeaders,
												acceptPost:     "application/json",
												acceptPatch:    "",
											})
										}

										return
									}

								}

							case 'q': // Prefix: "question/"

								if l := len("question/"); len(elem) >= l && elem[0:l] == "question/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "requestID"
								// Match until "/"
								idx := strings.IndexByte(elem, '/')
								if idx < 0 {
									idx = len(elem)
								}
								args[1] = elem[:idx]
								elem = elem[idx:]

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case '/': // Prefix: "/re"

									if l := len("/re"); len(elem) >= l && elem[0:l] == "/re" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										break
									}
									switch elem[0] {
									case 'j': // Prefix: "ject"

										if l := len("ject"); len(elem) >= l && elem[0:l] == "ject" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch r.Method {
											case "POST":
												s.handleV2SessionQuestionRejectRequest([2]string{
													args[0],
													args[1],
												}, elemIsEscaped, w, r)
											default:
												s.notAllowed(w, r, notAllowedParams{
													allowedMethods: "POST",
													allowedHeaders: nil,
													acceptPost:     "",
													acceptPatch:    "",
												})
											}

											return
										}

									case 'p': // Prefix: "ply"

										if l := len("ply"); len(elem) >= l && elem[0:l] == "ply" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch r.Method {
											case "POST":
												s.handleV2SessionQuestionReplyRequest([2]string{
													args[0],
													args[1],
												}, elemIsEscaped, w, r)
											default:
												s.notAllowed(w, r, notAllowedParams{
													allowedMethods: "POST",
													allowedHeaders: rn30AllowedHeaders,
													acceptPost:     "application/json",
													acceptPatch:    "",
												})
											}

											return
										}

									}

								}

							case 'w': // Prefix: "wait"

								if l := len("wait"); len(elem) >= l && elem[0:l] == "wait" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleV2SessionWaitRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "POST",
											allowedHeaders: nil,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							}

						}

					}

				}

			case 's': // Prefix: "session"

				if l := len("session"); len(elem) >= l && elem[0:l] == "session" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "POST":
						s.handleSessionCreateRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "POST",
							allowedHeaders: rn1AllowedHeaders,
							acceptPost:     "application/json",
							acceptPatch:    "",
						})
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "sessionID"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case '/': // Prefix: "/message"

						if l := len("/message"); len(elem) >= l && elem[0:l] == "/message" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleSessionMessagesRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							case "POST":
								s.handleSessionMessageRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET,POST",
									allowedHeaders: rn4AllowedHeaders,
									acceptPost:     "application/json",
									acceptPatch:    "",
								})
							}

							return
						}

					}

				}

			}

		}
	}
	s.notFound(w, r)
}

// Route is route object.
type Route struct {
	name           string
	summary        string
	operationID    string
	operationGroup string
	pathPattern    string
	count          int
	args           [2]string
}

// Name returns ogen operation name.
//
// It is guaranteed to be unique and not empty.
func (r Route) Name() string {
	return r.name
}

// Summary returns OpenAPI summary.
func (r Route) Summary() string {
	return r.summary
}

// OperationID returns OpenAPI operationId.
func (r Route) OperationID() string {
	return r.operationID
}

// OperationGroup returns the x-ogen-operation-group value.
func (r Route) OperationGroup() string {
	return r.operationGroup
}

// PathPattern returns OpenAPI path.
func (r Route) PathPattern() string {
	return r.pathPattern
}

// Args returns parsed arguments.
func (r Route) Args() []string {
	return r.args[:r.count]
}

// FindRoute finds Route for given method and path.
//
// Note: this method does not unescape path or handle reserved characters in path properly. Use FindPath instead.
func (s *Server) FindRoute(method, path string) (Route, bool) {
	return s.FindPath(method, &url.URL{Path: path})
}

// FindPath finds Route for given method and URL.
func (s *Server) FindPath(method string, u *url.URL) (r Route, _ bool) {
	var (
		elem = u.Path
		args = r.args
	)
	if rawPath := u.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
		}
		defer func() {
			for i, arg := range r.args[:r.count] {
				if unescaped, err := url.PathUnescape(arg); err == nil {
					r.args[i] = unescaped
				}
			}
		}()
	}

	elem, ok := s.cutPrefix(elem)
	if !ok {
		return r, false
	}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/"

			if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'a': // Prefix: "api/"

				if l := len("api/"); len(elem) >= l && elem[0:l] == "api/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'a': // Prefix: "agent"

					if l := len("agent"); len(elem) >= l && elem[0:l] == "agent" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = V2AgentListOperation
							r.summary = "List agents"
							r.operationID = "v2.agent.list"
							r.operationGroup = ""
							r.pathPattern = "/api/agent"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				case 'h': // Prefix: "health"

					if l := len("health"); len(elem) >= l && elem[0:l] == "health" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = V2HealthGetOperation
							r.summary = "Check server health"
							r.operationID = "v2.health.get"
							r.operationGroup = ""
							r.pathPattern = "/api/health"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				case 'm': // Prefix: "model"

					if l := len("model"); len(elem) >= l && elem[0:l] == "model" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = V2ModelListOperation
							r.summary = "List models"
							r.operationID = "v2.model.list"
							r.operationGroup = ""
							r.pathPattern = "/api/model"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				case 'p': // Prefix: "p"

					if l := len("p"); len(elem) >= l && elem[0:l] == "p" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'e': // Prefix: "ermission/request"

						if l := len("ermission/request"); len(elem) >= l && elem[0:l] == "ermission/request" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = V2PermissionRequestListOperation
								r.summary = "List pending permission requests"
								r.operationID = "v2.permission.request.list"
								r.operationGroup = ""
								r.pathPattern = "/api/permission/request"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					case 'r': // Prefix: "rovider"

						if l := len("rovider"); len(elem) >= l && elem[0:l] == "rovider" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = V2ProviderListOperation
								r.summary = "List providers"
								r.operationID = "v2.provider.list"
								r.operationGroup = ""
								r.pathPattern = "/api/provider"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					}

				case 'q': // Prefix: "question/request"

					if l := len("question/request"); len(elem) >= l && elem[0:l] == "question/request" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = V2QuestionRequestListOperation
							r.summary = "List pending question requests"
							r.operationID = "v2.question.request.list"
							r.operationGroup = ""
							r.pathPattern = "/api/question/request"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				case 's': // Prefix: "session"

					if l := len("session"); len(elem) >= l && elem[0:l] == "session" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = V2SessionListOperation
							r.summary = "List sessions"
							r.operationID = "v2.session.list"
							r.operationGroup = ""
							r.pathPattern = "/api/session"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "sessionID"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[0] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'c': // Prefix: "context"

								if l := len("context"); len(elem) >= l && elem[0:l] == "context" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "GET":
										r.name = V2SessionContextOperation
										r.summary = "Get session context"
										r.operationID = "v2.session.context"
										r.operationGroup = ""
										r.pathPattern = "/api/session/{sessionID}/context"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							case 'm': // Prefix: "message"

								if l := len("message"); len(elem) >= l && elem[0:l] == "message" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "GET":
										r.name = V2SessionMessagesOperation
										r.summary = "Get session messages"
										r.operationID = "v2.session.messages"
										r.operationGroup = ""
										r.pathPattern = "/api/session/{sessionID}/message"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							case 'p': // Prefix: "p"

								if l := len("p"); len(elem) >= l && elem[0:l] == "p" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'e': // Prefix: "ermission"

									if l := len("ermission"); len(elem) >= l && elem[0:l] == "ermission" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										switch method {
										case "GET":
											r.name = V2SessionPermissionListOperation
											r.summary = "List session permission requests"
											r.operationID = "v2.session.permission.list"
											r.operationGroup = ""
											r.pathPattern = "/api/session/{sessionID}/permission"
											r.args = args
											r.count = 1
											return r, true
										default:
											return
										}
									}
									switch elem[0] {
									case '/': // Prefix: "/"

										if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
											elem = elem[l:]
										} else {
											break
										}

										// Param: "requestID"
										// Match until "/"
										idx := strings.IndexByte(elem, '/')
										if idx < 0 {
											idx = len(elem)
										}
										args[1] = elem[:idx]
										elem = elem[idx:]

										if len(elem) == 0 {
											break
										}
										switch elem[0] {
										case '/': // Prefix: "/reply"

											if l := len("/reply"); len(elem) >= l && elem[0:l] == "/reply" {
												elem = elem[l:]
											} else {
												break
											}

											if len(elem) == 0 {
												// Leaf node.
												switch method {
												case "POST":
													r.name = V2SessionPermissionReplyOperation
													r.summary = "Reply to pending permission request"
													r.operationID = "v2.session.permission.reply"
													r.operationGroup = ""
													r.pathPattern = "/api/session/{sessionID}/permission/{requestID}/reply"
													r.args = args
													r.count = 2
													return r, true
												default:
													return
												}
											}

										}

									}

								case 'r': // Prefix: "rompt"

									if l := len("rompt"); len(elem) >= l && elem[0:l] == "rompt" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "POST":
											r.name = V2SessionPromptOperation
											r.summary = "Send message"
											r.operationID = "v2.session.prompt"
											r.operationGroup = ""
											r.pathPattern = "/api/session/{sessionID}/prompt"
											r.args = args
											r.count = 1
											return r, true
										default:
											return
										}
									}

								}

							case 'q': // Prefix: "question/"

								if l := len("question/"); len(elem) >= l && elem[0:l] == "question/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "requestID"
								// Match until "/"
								idx := strings.IndexByte(elem, '/')
								if idx < 0 {
									idx = len(elem)
								}
								args[1] = elem[:idx]
								elem = elem[idx:]

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case '/': // Prefix: "/re"

									if l := len("/re"); len(elem) >= l && elem[0:l] == "/re" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										break
									}
									switch elem[0] {
									case 'j': // Prefix: "ject"

										if l := len("ject"); len(elem) >= l && elem[0:l] == "ject" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch method {
											case "POST":
												r.name = V2SessionQuestionRejectOperation
												r.summary = "Reject pending question request"
												r.operationID = "v2.session.question.reject"
												r.operationGroup = ""
												r.pathPattern = "/api/session/{sessionID}/question/{requestID}/reject"
												r.args = args
												r.count = 2
												return r, true
											default:
												return
											}
										}

									case 'p': // Prefix: "ply"

										if l := len("ply"); len(elem) >= l && elem[0:l] == "ply" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch method {
											case "POST":
												r.name = V2SessionQuestionReplyOperation
												r.summary = "Reply to pending question request"
												r.operationID = "v2.session.question.reply"
												r.operationGroup = ""
												r.pathPattern = "/api/session/{sessionID}/question/{requestID}/reply"
												r.args = args
												r.count = 2
												return r, true
											default:
												return
											}
										}

									}

								}

							case 'w': // Prefix: "wait"

								if l := len("wait"); len(elem) >= l && elem[0:l] == "wait" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = V2SessionWaitOperation
										r.summary = "Wait for session"
										r.operationID = "v2.session.wait"
										r.operationGroup = ""
										r.pathPattern = "/api/session/{sessionID}/wait"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							}

						}

					}

				}

			case 's': // Prefix: "session"

				if l := len("session"); len(elem) >= l && elem[0:l] == "session" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "POST":
						r.name = SessionCreateOperation
						r.summary = "Create session"
						r.operationID = "session.create"
						r.operationGroup = ""
						r.pathPattern = "/session"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "sessionID"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case '/': // Prefix: "/message"

						if l := len("/message"); len(elem) >= l && elem[0:l] == "/message" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = SessionMessagesOperation
								r.summary = "Get session messages"
								r.operationID = "session.messages"
								r.operationGroup = ""
								r.pathPattern = "/session/{sessionID}/message"
								r.args = args
								r.count = 1
								return r, true
							case "POST":
								r.name = SessionMessageOperation
								r.summary = "Send message"
								r.operationID = "session.message"
								r.operationGroup = ""
								r.pathPattern = "/session/{sessionID}/message"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

					}

				}

			}

		}
	}
	return r, false
}
