// Code generated by ogen, DO NOT EDIT.

package opencodeapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// SessionCreate implements session.create operation.
//
// Create a new OpenCode session for interacting with AI assistants and managing conversations.
//
// POST /session
func (UnimplementedHandler) SessionCreate(ctx context.Context, req OptSessionCreateReq, params SessionCreateParams) (r SessionCreateRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SessionMessage implements session.message operation.
//
// Send a message to a session.
//
// POST /session/{sessionID}/message
func (UnimplementedHandler) SessionMessage(ctx context.Context, req *SessionMessageReq, params SessionMessageParams) (r SessionMessageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SessionMessages implements session.messages operation.
//
// Retrieve all messages in a session, including user prompts and AI responses.
//
// GET /session/{sessionID}/message
func (UnimplementedHandler) SessionMessages(ctx context.Context, params SessionMessagesParams) (r SessionMessagesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// V2AgentList implements v2.agent.list operation.
//
// Retrieve currently registered agents.
//
// GET /api/agent
func (UnimplementedHandler) V2AgentList(ctx context.Context, params V2AgentListParams) (r V2AgentListRes, _ error) {
	return r, ht.ErrNotImplemented
}

// V2HealthGet implements v2.health.get operation.
//
// Check whether the API server is ready to accept requests.
//
// GET /api/health
func (UnimplementedHandler) V2HealthGet(ctx context.Context) (r V2HealthGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// V2ModelList implements v2.model.list operation.
//
// Retrieve available models ordered by release date.
//
// GET /api/model
func (UnimplementedHandler) V2ModelList(ctx context.Context, params V2ModelListParams) (r V2ModelListRes, _ error) {
	return r, ht.ErrNotImplemented
}

// V2PermissionRequestList implements v2.permission.request.list operation.
//
// Retrieve pending permission requests for a location.
//
// GET /api/permission/request
func (UnimplementedHandler) V2PermissionRequestList(ctx context.Context, params V2PermissionRequestListParams) (r V2PermissionRequestListRes, _ error) {
	return r, ht.ErrNotImplemented
}

// V2ProviderList implements v2.provider.list operation.
//
// Retrieve active AI providers so clients can show provider availability and configuration.
//
// GET /api/provider
func (UnimplementedHandler) V2ProviderList(ctx context.Context, params V2ProviderListParams) (r V2ProviderListRes, _ error) {
	return r, ht.ErrNotImplemented
}

// V2QuestionRequestList implements v2.question.request.list operation.
//
// Retrieve pending question requests for a location.
//
// GET /api/question/request
func (UnimplementedHandler) V2QuestionRequestList(ctx context.Context, params V2QuestionRequestListParams) (r V2QuestionRequestListRes, _ error) {
	return r, ht.ErrNotImplemented
}

// V2SessionContext implements v2.session.context operation.
//
// Retrieve the active context messages for a session (all messages after the last compaction).
//
// GET /api/session/{sessionID}/context
func (UnimplementedHandler) V2SessionContext(ctx context.Context, params V2SessionContextParams) (r V2SessionContextRes, _ error) {
	return r, ht.ErrNotImplemented
}

// V2SessionList implements v2.session.list operation.
//
// Retrieve sessions in the requested order. Items keep that order across pages; use cursor.next or
// cursor.previous to move through the ordered list.
//
// GET /api/session
func (UnimplementedHandler) V2SessionList(ctx context.Context, params V2SessionListParams) (r V2SessionListRes, _ error) {
	return r, ht.ErrNotImplemented
}

// V2SessionMessages implements v2.session.messages operation.
//
// Retrieve projected messages for a session. Items keep the requested order across pages; use
// cursor.next or cursor.previous to move through the ordered timeline.
//
// GET /api/session/{sessionID}/message
func (UnimplementedHandler) V2SessionMessages(ctx context.Context, params V2SessionMessagesParams) (r V2SessionMessagesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// V2SessionPermissionList implements v2.session.permission.list operation.
//
// Retrieve pending permission requests owned by a session.
//
// GET /api/session/{sessionID}/permission
func (UnimplementedHandler) V2SessionPermissionList(ctx context.Context, params V2SessionPermissionListParams) (r V2SessionPermissionListRes, _ error) {
	return r, ht.ErrNotImplemented
}

// V2SessionPermissionReply implements v2.session.permission.reply operation.
//
// Respond to a pending permission request owned by a session.
//
// POST /api/session/{sessionID}/permission/{requestID}/reply
func (UnimplementedHandler) V2SessionPermissionReply(ctx context.Context, req *V2SessionPermissionReplyReq, params V2SessionPermissionReplyParams) (r V2SessionPermissionReplyRes, _ error) {
	return r, ht.ErrNotImplemented
}

// V2SessionPrompt implements v2.session.prompt operation.
//
// Durably admit one session input and schedule agent-loop execution unless resume is false.
//
// POST /api/session/{sessionID}/prompt
func (UnimplementedHandler) V2SessionPrompt(ctx context.Context, req *V2SessionPromptReq, params V2SessionPromptParams) (r V2SessionPromptRes, _ error) {
	return r, ht.ErrNotImplemented
}

// V2SessionQuestionReject implements v2.session.question.reject operation.
//
// Reject a pending question request owned by a session.
//
// POST /api/session/{sessionID}/question/{requestID}/reject
func (UnimplementedHandler) V2SessionQuestionReject(ctx context.Context, params V2SessionQuestionRejectParams) (r V2SessionQuestionRejectRes, _ error) {
	return r, ht.ErrNotImplemented
}

// V2SessionQuestionReply implements v2.session.question.reply operation.
//
// Answer a pending question request owned by a session.
//
// POST /api/session/{sessionID}/question/{requestID}/reply
func (UnimplementedHandler) V2SessionQuestionReply(ctx context.Context, req *QuestionV2Reply, params V2SessionQuestionReplyParams) (r V2SessionQuestionReplyRes, _ error) {
	return r, ht.ErrNotImplemented
}

// V2SessionWait implements v2.session.wait operation.
//
// Wait for a session agent loop to become idle.
//
// POST /api/session/{sessionID}/wait
func (UnimplementedHandler) V2SessionWait(ctx context.Context, params V2SessionWaitParams) (r V2SessionWaitRes, _ error) {
	return r, ht.ErrNotImplemented
}
