// Code generated by ogen, DO NOT EDIT.

package opencodeapi

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// SessionCreate implements session.create operation.
	//
	// Create a new OpenCode session for interacting with AI assistants and managing conversations.
	//
	// POST /session
	SessionCreate(ctx context.Context, req OptSessionCreateReq, params SessionCreateParams) (SessionCreateRes, error)
	// SessionMessage implements session.message operation.
	//
	// Send a message to a session.
	//
	// POST /session/{sessionID}/message
	SessionMessage(ctx context.Context, req *SessionMessageReq, params SessionMessageParams) (SessionMessageRes, error)
	// SessionMessages implements session.messages operation.
	//
	// Retrieve all messages in a session, including user prompts and AI responses.
	//
	// GET /session/{sessionID}/message
	SessionMessages(ctx context.Context, params SessionMessagesParams) (SessionMessagesRes, error)
	// V2AgentList implements v2.agent.list operation.
	//
	// Retrieve currently registered agents.
	//
	// GET /api/agent
	V2AgentList(ctx context.Context, params V2AgentListParams) (V2AgentListRes, error)
	// V2HealthGet implements v2.health.get operation.
	//
	// Check whether the API server is ready to accept requests.
	//
	// GET /api/health
	V2HealthGet(ctx context.Context) (V2HealthGetRes, error)
	// V2ModelList implements v2.model.list operation.
	//
	// Retrieve available models ordered by release date.
	//
	// GET /api/model
	V2ModelList(ctx context.Context, params V2ModelListParams) (V2ModelListRes, error)
	// V2PermissionRequestList implements v2.permission.request.list operation.
	//
	// Retrieve pending permission requests for a location.
	//
	// GET /api/permission/request
	V2PermissionRequestList(ctx context.Context, params V2PermissionRequestListParams) (V2PermissionRequestListRes, error)
	// V2ProviderList implements v2.provider.list operation.
	//
	// Retrieve active AI providers so clients can show provider availability and configuration.
	//
	// GET /api/provider
	V2ProviderList(ctx context.Context, params V2ProviderListParams) (V2ProviderListRes, error)
	// V2QuestionRequestList implements v2.question.request.list operation.
	//
	// Retrieve pending question requests for a location.
	//
	// GET /api/question/request
	V2QuestionRequestList(ctx context.Context, params V2QuestionRequestListParams) (V2QuestionRequestListRes, error)
	// V2SessionContext implements v2.session.context operation.
	//
	// Retrieve the active context messages for a session (all messages after the last compaction).
	//
	// GET /api/session/{sessionID}/context
	V2SessionContext(ctx context.Context, params V2SessionContextParams) (V2SessionContextRes, error)
	// V2SessionList implements v2.session.list operation.
	//
	// Retrieve sessions in the requested order. Items keep that order across pages; use cursor.next or
	// cursor.previous to move through the ordered list.
	//
	// GET /api/session
	V2SessionList(ctx context.Context, params V2SessionListParams) (V2SessionListRes, error)
	// V2SessionMessages implements v2.session.messages operation.
	//
	// Retrieve projected messages for a session. Items keep the requested order across pages; use
	// cursor.next or cursor.previous to move through the ordered timeline.
	//
	// GET /api/session/{sessionID}/message
	V2SessionMessages(ctx context.Context, params V2SessionMessagesParams) (V2SessionMessagesRes, error)
	// V2SessionPermissionList implements v2.session.permission.list operation.
	//
	// Retrieve pending permission requests owned by a session.
	//
	// GET /api/session/{sessionID}/permission
	V2SessionPermissionList(ctx context.Context, params V2SessionPermissionListParams) (V2SessionPermissionListRes, error)
	// V2SessionPermissionReply implements v2.session.permission.reply operation.
	//
	// Respond to a pending permission request owned by a session.
	//
	// POST /api/session/{sessionID}/permission/{requestID}/reply
	V2SessionPermissionReply(ctx context.Context, req *V2SessionPermissionReplyReq, params V2SessionPermissionReplyParams) (V2SessionPermissionReplyRes, error)
	// V2SessionPrompt implements v2.session.prompt operation.
	//
	// Durably admit one session input and schedule agent-loop execution unless resume is false.
	//
	// POST /api/session/{sessionID}/prompt
	V2SessionPrompt(ctx context.Context, req *V2SessionPromptReq, params V2SessionPromptParams) (V2SessionPromptRes, error)
	// V2SessionQuestionReject implements v2.session.question.reject operation.
	//
	// Reject a pending question request owned by a session.
	//
	// POST /api/session/{sessionID}/question/{requestID}/reject
	V2SessionQuestionReject(ctx context.Context, params V2SessionQuestionRejectParams) (V2SessionQuestionRejectRes, error)
	// V2SessionQuestionReply implements v2.session.question.reply operation.
	//
	// Answer a pending question request owned by a session.
	//
	// POST /api/session/{sessionID}/question/{requestID}/reply
	V2SessionQuestionReply(ctx context.Context, req *QuestionV2Reply, params V2SessionQuestionReplyParams) (V2SessionQuestionReplyRes, error)
	// V2SessionWait implements v2.session.wait operation.
	//
	// Wait for a session agent loop to become idle.
	//
	// POST /api/session/{sessionID}/wait
	V2SessionWait(ctx context.Context, params V2SessionWaitParams) (V2SessionWaitRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
