// Code generated by ogen, DO NOT EDIT.

package opencodeapi

// OperationName is the ogen operation name
type OperationName = string

const (
	SessionCreateOperation            OperationName = "SessionCreate"
	SessionMessageOperation           OperationName = "SessionMessage"
	SessionMessagesOperation          OperationName = "SessionMessages"
	V2AgentListOperation              OperationName = "V2AgentList"
	V2HealthGetOperation              OperationName = "V2HealthGet"
	V2ModelListOperation              OperationName = "V2ModelList"
	V2PermissionRequestListOperation  OperationName = "V2PermissionRequestList"
	V2ProviderListOperation           OperationName = "V2ProviderList"
	V2QuestionRequestListOperation    OperationName = "V2QuestionRequestList"
	V2SessionContextOperation         OperationName = "V2SessionContext"
	V2SessionListOperation            OperationName = "V2SessionList"
	V2SessionMessagesOperation        OperationName = "V2SessionMessages"
	V2SessionPermissionListOperation  OperationName = "V2SessionPermissionList"
	V2SessionPermissionReplyOperation OperationName = "V2SessionPermissionReply"
	V2SessionPromptOperation          OperationName = "V2SessionPrompt"
	V2SessionQuestionRejectOperation  OperationName = "V2SessionQuestionReject"
	V2SessionQuestionReplyOperation   OperationName = "V2SessionQuestionReply"
	V2SessionWaitOperation            OperationName = "V2SessionWait"
)
