// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package opencode

import (
	"context"
	"sync"

	"github.com/pradhankukiran/codex-opencode-executor/internal/tools/opencode/opencodeapi"
)

// Ensure, that HandlerMock does implement opencodeapi.Handler.
// If this is not the case, regenerate this file with moq.
var _ opencodeapi.Handler = &HandlerMock{}

// HandlerMock is a mock implementation of opencodeapi.Handler.
//
//	func TestSomethingThatUsesHandler(t *testing.T) {
//
//		// make and configure a mocked opencodeapi.Handler
//		mockedHandler := &HandlerMock{
//			SessionCreateFunc: func(ctx context.Context, req opencodeapi.OptSessionCreateReq, params opencodeapi.SessionCreateParams) (opencodeapi.SessionCreateRes, error) {
//				panic("mock out the SessionCreate method")
//			},
//			SessionMessageFunc: func(ctx context.Context, req *opencodeapi.SessionMessageReq, params opencodeapi.SessionMessageParams) (opencodeapi.SessionMessageRes, error) {
//				panic("mock out the SessionMessage method")
//			},
//			SessionMessagesFunc: func(ctx context.Context, params opencodeapi.SessionMessagesParams) (opencodeapi.SessionMessagesRes, error) {
//				panic("mock out the SessionMessages method")
//			},
//			V2AgentListFunc: func(ctx context.Context, params opencodeapi.V2AgentListParams) (opencodeapi.V2AgentListRes, error) {
//				panic("mock out the V2AgentList method")
//			},
//			V2HealthGetFunc: func(ctx context.Context) (opencodeapi.V2HealthGetRes, error) {
//				panic("mock out the V2HealthGet method")
//			},
//			V2ModelListFunc: func(ctx context.Context, params opencodeapi.V2ModelListParams) (opencodeapi.V2ModelListRes, error) {
//				panic("mock out the V2ModelList method")
//			},
//			V2PermissionRequestListFunc: func(ctx context.Context, params opencodeapi.V2PermissionRequestListParams) (opencodeapi.V2PermissionRequestListRes, error) {
//				panic("mock out the V2PermissionRequestList method")
//			},
//			V2ProviderListFunc: func(ctx context.Context, params opencodeapi.V2ProviderListParams) (opencodeapi.V2ProviderListRes, error) {
//				panic("mock out the V2ProviderList method")
//			},
//			V2QuestionRequestListFunc: func(ctx context.Context, params opencodeapi.V2QuestionRequestListParams) (opencodeapi.V2QuestionRequestListRes, error) {
//				panic("mock out the V2QuestionRequestList method")
//			},
//			V2SessionContextFunc: func(ctx context.Context, params opencodeapi.V2SessionContextParams) (opencodeapi.V2SessionContextRes, error) {
//				panic("mock out the V2SessionContext method")
//			},
//			V2SessionListFunc: func(ctx context.Context, params opencodeapi.V2SessionListParams) (opencodeapi.V2SessionListRes, error) {
//				panic("mock out the V2SessionList method")
//			},
//			V2SessionMessagesFunc: func(ctx context.Context, params opencodeapi.V2SessionMessagesParams) (opencodeapi.V2SessionMessagesRes, error) {
//				panic("mock out the V2SessionMessages method")
//			},
//			V2SessionPermissionListFunc: func(ctx context.Context, params opencodeapi.V2SessionPermissionListParams) (opencodeapi.V2SessionPermissionListRes, error) {
//				panic("mock out the V2SessionPermissionList method")
//			},
//			V2SessionPermissionReplyFunc: func(ctx context.Context, req *opencodeapi.V2SessionPermissionReplyReq, params opencodeapi.V2SessionPermissionReplyParams) (opencodeapi.V2SessionPermissionReplyRes, error) {
//				panic("mock out the V2SessionPermissionReply method")
//			},
//			V2SessionPromptFunc: func(ctx context.Context, req *opencodeapi.V2SessionPromptReq, params opencodeapi.V2SessionPromptParams) (opencodeapi.V2SessionPromptRes, error) {
//				panic("mock out the V2SessionPrompt method")
//			},
//			V2SessionQuestionRejectFunc: func(ctx context.Context, params opencodeapi.V2SessionQuestionRejectParams) (opencodeapi.V2SessionQuestionRejectRes, error) {
//				panic("mock out the V2SessionQuestionReject method")
//			},
//			V2SessionQuestionReplyFunc: func(ctx context.Context, req *opencodeapi.QuestionV2Reply, params opencodeapi.V2SessionQuestionReplyParams) (opencodeapi.V2SessionQuestionReplyRes, error) {
//				panic("mock out the V2SessionQuestionReply method")
//			},
//			V2SessionWaitFunc: func(ctx context.Context, params opencodeapi.V2SessionWaitParams) (opencodeapi.V2SessionWaitRes, error) {
//				panic("mock out the V2SessionWait method")
//			},
//		}
//
//		// use mockedHandler in code that requires opencodeapi.Handler
//		// and then make assertions.
//
//	}
type HandlerMock struct {
	// SessionCreateFunc mocks the SessionCreate method.
	SessionCreateFunc func(ctx context.Context, req opencodeapi.OptSessionCreateReq, params opencodeapi.SessionCreateParams) (opencodeapi.SessionCreateRes, error)

	// SessionMessageFunc mocks the SessionMessage method.
	SessionMessageFunc func(ctx context.Context, req *opencodeapi.SessionMessageReq, params opencodeapi.SessionMessageParams) (opencodeapi.SessionMessageRes, error)

	// SessionMessagesFunc mocks the SessionMessages method.
	SessionMessagesFunc func(ctx context.Context, params opencodeapi.SessionMessagesParams) (opencodeapi.SessionMessagesRes, error)

	// V2AgentListFunc mocks the V2AgentList method.
	V2AgentListFunc func(ctx context.Context, params opencodeapi.V2AgentListParams) (opencodeapi.V2AgentListRes, error)

	// V2HealthGetFunc mocks the V2HealthGet method.
	V2HealthGetFunc func(ctx context.Context) (opencodeapi.V2HealthGetRes, error)

	// V2ModelListFunc mocks the V2ModelList method.
	V2ModelListFunc func(ctx context.Context, params opencodeapi.V2ModelListParams) (opencodeapi.V2ModelListRes, error)

	// V2PermissionRequestListFunc mocks the V2PermissionRequestList method.
	V2PermissionRequestListFunc func(ctx context.Context, params opencodeapi.V2PermissionRequestListParams) (opencodeapi.V2PermissionRequestListRes, error)

	// V2ProviderListFunc mocks the V2ProviderList method.
	V2ProviderListFunc func(ctx context.Context, params opencodeapi.V2ProviderListParams) (opencodeapi.V2ProviderListRes, error)

	// V2QuestionRequestListFunc mocks the V2QuestionRequestList method.
	V2QuestionRequestListFunc func(ctx context.Context, params opencodeapi.V2QuestionRequestListParams) (opencodeapi.V2QuestionRequestListRes, error)

	// V2SessionContextFunc mocks the V2SessionContext method.
	V2SessionContextFunc func(ctx context.Context, params opencodeapi.V2SessionContextParams) (opencodeapi.V2SessionContextRes, error)

	// V2SessionListFunc mocks the V2SessionList method.
	V2SessionListFunc func(ctx context.Context, params opencodeapi.V2SessionListParams) (opencodeapi.V2SessionListRes, error)

	// V2SessionMessagesFunc mocks the V2SessionMessages method.
	V2SessionMessagesFunc func(ctx context.Context, params opencodeapi.V2SessionMessagesParams) (opencodeapi.V2SessionMessagesRes, error)

	// V2SessionPermissionListFunc mocks the V2SessionPermissionList method.
	V2SessionPermissionListFunc func(ctx context.Context, params opencodeapi.V2SessionPermissionListParams) (opencodeapi.V2SessionPermissionListRes, error)

	// V2SessionPermissionReplyFunc mocks the V2SessionPermissionReply method.
	V2SessionPermissionReplyFunc func(ctx context.Context, req *opencodeapi.V2SessionPermissionReplyReq, params opencodeapi.V2SessionPermissionReplyParams) (opencodeapi.V2SessionPermissionReplyRes, error)

	// V2SessionPromptFunc mocks the V2SessionPrompt method.
	V2SessionPromptFunc func(ctx context.Context, req *opencodeapi.V2SessionPromptReq, params opencodeapi.V2SessionPromptParams) (opencodeapi.V2SessionPromptRes, error)

	// V2SessionQuestionRejectFunc mocks the V2SessionQuestionReject method.
	V2SessionQuestionRejectFunc func(ctx context.Context, params opencodeapi.V2SessionQuestionRejectParams) (opencodeapi.V2SessionQuestionRejectRes, error)

	// V2SessionQuestionReplyFunc mocks the V2SessionQuestionReply method.
	V2SessionQuestionReplyFunc func(ctx context.Context, req *opencodeapi.QuestionV2Reply, params opencodeapi.V2SessionQuestionReplyParams) (opencodeapi.V2SessionQuestionReplyRes, error)

	// V2SessionWaitFunc mocks the V2SessionWait method.
	V2SessionWaitFunc func(ctx context.Context, params opencodeapi.V2SessionWaitParams) (opencodeapi.V2SessionWaitRes, error)

	// calls tracks calls to the methods.
	calls struct {
		// SessionCreate holds details about calls to the SessionCreate method.
		SessionCreate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req opencodeapi.OptSessionCreateReq
			// Params is the params argument value.
			Params opencodeapi.SessionCreateParams
		}
		// SessionMessage holds details about calls to the SessionMessage method.
		SessionMessage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *opencodeapi.SessionMessageReq
			// Params is the params argument value.
			Params opencodeapi.SessionMessageParams
		}
		// SessionMessages holds details about calls to the SessionMessages method.
		SessionMessages []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params opencodeapi.SessionMessagesParams
		}
		// V2AgentList holds details about calls to the V2AgentList method.
		V2AgentList []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params opencodeapi.V2AgentListParams
		}
		// V2HealthGet holds details about calls to the V2HealthGet method.
		V2HealthGet []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// V2ModelList holds details about calls to the V2ModelList method.
		V2ModelList []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params opencodeapi.V2ModelListParams
		}
		// V2PermissionRequestList holds details about calls to the V2PermissionRequestList method.
		V2PermissionRequestList []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params opencodeapi.V2PermissionRequestListParams
		}
		// V2ProviderList holds details about calls to the V2ProviderList method.
		V2ProviderList []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params opencodeapi.V2ProviderListParams
		}
		// V2QuestionRequestList holds details about calls to the V2QuestionRequestList method.
		V2QuestionRequestList []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params opencodeapi.V2QuestionRequestListParams
		}
		// V2SessionContext holds details about calls to the V2SessionContext method.
		V2SessionContext []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params opencodeapi.V2SessionContextParams
		}
		// V2SessionList holds details about calls to the V2SessionList method.
		V2SessionList []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params opencodeapi.V2SessionListParams
		}
		// V2SessionMessages holds details about calls to the V2SessionMessages method.
		V2SessionMessages []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params opencodeapi.V2SessionMessagesParams
		}
		// V2SessionPermissionList holds details about calls to the V2SessionPermissionList method.
		V2SessionPermissionList []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params opencodeapi.V2SessionPermissionListParams
		}
		// V2SessionPermissionReply holds details about calls to the V2SessionPermissionReply method.
		V2SessionPermissionReply []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *opencodeapi.V2SessionPermissionReplyReq
			// Params is the params argument value.
			Params opencodeapi.V2SessionPermissionReplyParams
		}
		// V2SessionPrompt holds details about calls to the V2SessionPrompt method.
		V2SessionPrompt []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *opencodeapi.V2SessionPromptReq
			// Params is the params argument value.
			Params opencodeapi.V2SessionPromptParams
		}
		// V2SessionQuestionReject holds details about calls to the V2SessionQuestionReject method.
		V2SessionQuestionReject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params opencodeapi.V2SessionQuestionRejectParams
		}
		// V2SessionQuestionReply holds details about calls to the V2SessionQuestionReply method.
		V2SessionQuestionReply []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *opencodeapi.QuestionV2Reply
			// Params is the params argument value.
			Params opencodeapi.V2SessionQuestionReplyParams
		}
		// V2SessionWait holds details about calls to the V2SessionWait method.
		V2SessionWait []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params opencodeapi.V2SessionWaitParams
		}
	}
	lockSessionCreate            sync.RWMutex
	lockSessionMessage           sync.RWMutex
	lockSessionMessages          sync.RWMutex
	lockV2AgentList              sync.RWMutex
	lockV2HealthGet              sync.RWMutex
	lockV2ModelList              sync.RWMutex
	lockV2PermissionRequestList  sync.RWMutex
	lockV2ProviderList           sync.RWMutex
	lockV2QuestionRequestList    sync.RWMutex
	lockV2SessionContext         sync.RWMutex
	lockV2SessionList            sync.RWMutex
	lockV2SessionMessages        sync.RWMutex
	lockV2SessionPermissionList  sync.RWMutex
	lockV2SessionPermissionReply sync.RWMutex
	lockV2SessionPrompt          sync.RWMutex
	lockV2SessionQuestionReject  sync.RWMutex
	lockV2SessionQuestionReply   sync.RWMutex
	lockV2SessionWait            sync.RWMutex
}

// SessionCreate calls SessionCreateFunc.
func (mock *HandlerMock) SessionCreate(ctx context.Context, req opencodeapi.OptSessionCreateReq, params opencodeapi.SessionCreateParams) (opencodeapi.SessionCreateRes, error) {
	if mock.SessionCreateFunc == nil {
		panic("HandlerMock.SessionCreateFunc: method is nil but Handler.SessionCreate was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Req    opencodeapi.OptSessionCreateReq
		Params opencodeapi.SessionCreateParams
	}{
		Ctx:    ctx,
		Req:    req,
		Params: params,
	}
	mock.lockSessionCreate.Lock()
	mock.calls.SessionCreate = append(mock.calls.SessionCreate, callInfo)
	mock.lockSessionCreate.Unlock()
	return mock.SessionCreateFunc(ctx, req, params)
}

// SessionCreateCalls gets all the calls that were made to SessionCreate.
// Check the length with:
//
//	len(mockedHandler.SessionCreateCalls())
func (mock *HandlerMock) SessionCreateCalls() []struct {
	Ctx    context.Context
	Req    opencodeapi.OptSessionCreateReq
	Params opencodeapi.SessionCreateParams
} {
	var calls []struct {
		Ctx    context.Context
		Req    opencodeapi.OptSessionCreateReq
		Params opencodeapi.SessionCreateParams
	}
	mock.lockSessionCreate.RLock()
	calls = mock.calls.SessionCreate
	mock.lockSessionCreate.RUnlock()
	return calls
}

// SessionMessage calls SessionMessageFunc.
func (mock *HandlerMock) SessionMessage(ctx context.Context, req *opencodeapi.SessionMessageReq, params opencodeapi.SessionMessageParams) (opencodeapi.SessionMessageRes, error) {
	if mock.SessionMessageFunc == nil {
		panic("HandlerMock.SessionMessageFunc: method is nil but Handler.SessionMessage was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Req    *opencodeapi.SessionMessageReq
		Params opencodeapi.SessionMessageParams
	}{
		Ctx:    ctx,
		Req:    req,
		Params: params,
	}
	mock.lockSessionMessage.Lock()
	mock.calls.SessionMessage = append(mock.calls.SessionMessage, callInfo)
	mock.lockSessionMessage.Unlock()
	return mock.SessionMessageFunc(ctx, req, params)
}

// SessionMessageCalls gets all the calls that were made to SessionMessage.
// Check the length with:
//
//	len(mockedHandler.SessionMessageCalls())
func (mock *HandlerMock) SessionMessageCalls() []struct {
	Ctx    context.Context
	Req    *opencodeapi.SessionMessageReq
	Params opencodeapi.SessionMessageParams
} {
	var calls []struct {
		Ctx    context.Context
		Req    *opencodeapi.SessionMessageReq
		Params opencodeapi.SessionMessageParams
	}
	mock.lockSessionMessage.RLock()
	calls = mock.calls.SessionMessage
	mock.lockSessionMessage.RUnlock()
	return calls
}

// SessionMessages calls SessionMessagesFunc.
func (mock *HandlerMock) SessionMessages(ctx context.Context, params opencodeapi.SessionMessagesParams) (opencodeapi.SessionMessagesRes, error) {
	if mock.SessionMessagesFunc == nil {
		panic("HandlerMock.SessionMessagesFunc: method is nil but Handler.SessionMessages was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params opencodeapi.SessionMessagesParams
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockSessionMessages.Lock()
	mock.calls.SessionMessages = append(mock.calls.SessionMessages, callInfo)
	mock.lockSessionMessages.Unlock()
	return mock.SessionMessagesFunc(ctx, params)
}

// SessionMessagesCalls gets all the calls that were made to SessionMessages.
// Check the length with:
//
//	len(mockedHandler.SessionMessagesCalls())
func (mock *HandlerMock) SessionMessagesCalls() []struct {
	Ctx    context.Context
	Params opencodeapi.SessionMessagesParams
} {
	var calls []struct {
		Ctx    context.Context
		Params opencodeapi.SessionMessagesParams
	}
	mock.lockSessionMessages.RLock()
	calls = mock.calls.SessionMessages
	mock.lockSessionMessages.RUnlock()
	return calls
}

// V2AgentList calls V2AgentListFunc.
func (mock *HandlerMock) V2AgentList(ctx context.Context, params opencodeapi.V2AgentListParams) (opencodeapi.V2AgentListRes, error) {
	if mock.V2AgentListFunc == nil {
		panic("HandlerMock.V2AgentListFunc: method is nil but Handler.V2AgentList was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params opencodeapi.V2AgentListParams
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockV2AgentList.Lock()
	mock.calls.V2AgentList = append(mock.calls.V2AgentList, callInfo)
	mock.lockV2AgentList.Unlock()
	return mock.V2AgentListFunc(ctx, params)
}

// V2AgentListCalls gets all the calls that were made to V2AgentList.
// Check the length with:
//
//	len(mockedHandler.V2AgentListCalls())
func (mock *HandlerMock) V2AgentListCalls() []struct {
	Ctx    context.Context
	Params opencodeapi.V2AgentListParams
} {
	var calls []struct {
		Ctx    context.Context
		Params opencodeapi.V2AgentListParams
	}
	mock.lockV2AgentList.RLock()
	calls = mock.calls.V2AgentList
	mock.lockV2AgentList.RUnlock()
	return calls
}

// V2HealthGet calls V2HealthGetFunc.
func (mock *HandlerMock) V2HealthGet(ctx context.Context) (opencodeapi.V2HealthGetRes, error) {
	if mock.V2HealthGetFunc == nil {
		panic("HandlerMock.V2HealthGetFunc: method is nil but Handler.V2HealthGet was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockV2HealthGet.Lock()
	mock.calls.V2HealthGet = append(mock.calls.V2HealthGet, callInfo)
	mock.lockV2HealthGet.Unlock()
	return mock.V2HealthGetFunc(ctx)
}

// V2HealthGetCalls gets all the calls that were made to V2HealthGet.
// Check the length with:
//
//	len(mockedHandler.V2HealthGetCalls())
func (mock *HandlerMock) V2HealthGetCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockV2HealthGet.RLock()
	calls = mock.calls.V2HealthGet
	mock.lockV2HealthGet.RUnlock()
	return calls
}

// V2ModelList calls V2ModelListFunc.
func (mock *HandlerMock) V2ModelList(ctx context.Context, params opencodeapi.V2ModelListParams) (opencodeapi.V2ModelListRes, error) {
	if mock.V2ModelListFunc == nil {
		panic("HandlerMock.V2ModelListFunc: method is nil but Handler.V2ModelList was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params opencodeapi.V2ModelListParams
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockV2ModelList.Lock()
	mock.calls.V2ModelList = append(mock.calls.V2ModelList, callInfo)
	mock.lockV2ModelList.Unlock()
	return mock.V2ModelListFunc(ctx, params)
}

// V2ModelListCalls gets all the calls that were made to V2ModelList.
// Check the length with:
//
//	len(mockedHandler.V2ModelListCalls())
func (mock *HandlerMock) V2ModelListCalls() []struct {
	Ctx    context.Context
	Params opencodeapi.V2ModelListParams
} {
	var calls []struct {
		Ctx    context.Context
		Params opencodeapi.V2ModelListParams
	}
	mock.lockV2ModelList.RLock()
	calls = mock.calls.V2ModelList
	mock.lockV2ModelList.RUnlock()
	return calls
}

// V2PermissionRequestList calls V2PermissionRequestListFunc.
func (mock *HandlerMock) V2PermissionRequestList(ctx context.Context, params opencodeapi.V2PermissionRequestListParams) (opencodeapi.V2PermissionRequestListRes, error) {
	if mock.V2PermissionRequestListFunc == nil {
		panic("HandlerMock.V2PermissionRequestListFunc: method is nil but Handler.V2PermissionRequestList was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params opencodeapi.V2PermissionRequestListParams
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockV2PermissionRequestList.Lock()
	mock.calls.V2PermissionRequestList = append(mock.calls.V2PermissionRequestList, callInfo)
	mock.lockV2PermissionRequestList.Unlock()
	return mock.V2PermissionRequestListFunc(ctx, params)
}

// V2PermissionRequestListCalls gets all the calls that were made to V2PermissionRequestList.
// Check the length with:
//
//	len(mockedHandler.V2PermissionRequestListCalls())
func (mock *HandlerMock) V2PermissionRequestListCalls() []struct {
	Ctx    context.Context
	Params opencodeapi.V2PermissionRequestListParams
} {
	var calls []struct {
		Ctx    context.Context
		Params opencodeapi.V2PermissionRequestListParams
	}
	mock.lockV2PermissionRequestList.RLock()
	calls = mock.calls.V2PermissionRequestList
	mock.lockV2PermissionRequestList.RUnlock()
	return calls
}

// V2ProviderList calls V2ProviderListFunc.
func (mock *HandlerMock) V2ProviderList(ctx context.Context, params opencodeapi.V2ProviderListParams) (opencodeapi.V2ProviderListRes, error) {
	if mock.V2ProviderListFunc == nil {
		panic("HandlerMock.V2ProviderListFunc: method is nil but Handler.V2ProviderList was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params opencodeapi.V2ProviderListParams
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockV2ProviderList.Lock()
	mock.calls.V2ProviderList = append(mock.calls.V2ProviderList, callInfo)
	mock.lockV2ProviderList.Unlock()
	return mock.V2ProviderListFunc(ctx, params)
}

// V2ProviderListCalls gets all the calls that were made to V2ProviderList.
// Check the length with:
//
//	len(mockedHandler.V2ProviderListCalls())
func (mock *HandlerMock) V2ProviderListCalls() []struct {
	Ctx    context.Context
	Params opencodeapi.V2ProviderListParams
} {
	var calls []struct {
		Ctx    context.Context
		Params opencodeapi.V2ProviderListParams
	}
	mock.lockV2ProviderList.RLock()
	calls = mock.calls.V2ProviderList
	mock.lockV2ProviderList.RUnlock()
	return calls
}

// V2QuestionRequestList calls V2QuestionRequestListFunc.
func (mock *HandlerMock) V2QuestionRequestList(ctx context.Context, params opencodeapi.V2QuestionRequestListParams) (opencodeapi.V2QuestionRequestListRes, error) {
	if mock.V2QuestionRequestListFunc == nil {
		panic("HandlerMock.V2QuestionRequestListFunc: method is nil but Handler.V2QuestionRequestList was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params opencodeapi.V2QuestionRequestListParams
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockV2QuestionRequestList.Lock()
	mock.calls.V2QuestionRequestList = append(mock.calls.V2QuestionRequestList, callInfo)
	mock.lockV2QuestionRequestList.Unlock()
	return mock.V2QuestionRequestListFunc(ctx, params)
}

// V2QuestionRequestListCalls gets all the calls that were made to V2QuestionRequestList.
// Check the length with:
//
//	len(mockedHandler.V2QuestionRequestListCalls())
func (mock *HandlerMock) V2QuestionRequestListCalls() []struct {
	Ctx    context.Context
	Params opencodeapi.V2QuestionRequestListParams
} {
	var calls []struct {
		Ctx    context.Context
		Params opencodeapi.V2QuestionRequestListParams
	}
	mock.lockV2QuestionRequestList.RLock()
	calls = mock.calls.V2QuestionRequestList
	mock.lockV2QuestionRequestList.RUnlock()
	return calls
}

// V2SessionContext calls V2SessionContextFunc.
func (mock *HandlerMock) V2SessionContext(ctx context.Context, params opencodeapi.V2SessionContextParams) (opencodeapi.V2SessionContextRes, error) {
	if mock.V2SessionContextFunc == nil {
		panic("HandlerMock.V2SessionContextFunc: method is nil but Handler.V2SessionContext was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params opencodeapi.V2SessionContextParams
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockV2SessionContext.Lock()
	mock.calls.V2SessionContext = append(mock.calls.V2SessionContext, callInfo)
	mock.lockV2SessionContext.Unlock()
	return mock.V2SessionContextFunc(ctx, params)
}

// V2SessionContextCalls gets all the calls that were made to V2SessionContext.
// Check the length with:
//
//	len(mockedHandler.V2SessionContextCalls())
func (mock *HandlerMock) V2SessionContextCalls() []struct {
	Ctx    context.Context
	Params opencodeapi.V2SessionContextParams
} {
	var calls []struct {
		Ctx    context.Context
		Params opencodeapi.V2SessionContextParams
	}
	mock.lockV2SessionContext.RLock()
	calls = mock.calls.V2SessionContext
	mock.lockV2SessionContext.RUnlock()
	return calls
}

// V2SessionList calls V2SessionListFunc.
func (mock *HandlerMock) V2SessionList(ctx context.Context, params opencodeapi.V2SessionListParams) (opencodeapi.V2SessionListRes, error) {
	if mock.V2SessionListFunc == nil {
		panic("HandlerMock.V2SessionListFunc: method is nil but Handler.V2SessionList was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params opencodeapi.V2SessionListParams
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockV2SessionList.Lock()
	mock.calls.V2SessionList = append(mock.calls.V2SessionList, callInfo)
	mock.lockV2SessionList.Unlock()
	return mock.V2SessionListFunc(ctx, params)
}

// V2SessionListCalls gets all the calls that were made to V2SessionList.
// Check the length with:
//
//	len(mockedHandler.V2SessionListCalls())
func (mock *HandlerMock) V2SessionListCalls() []struct {
	Ctx    context.Context
	Params opencodeapi.V2SessionListParams
} {
	var calls []struct {
		Ctx    context.Context
		Params opencodeapi.V2SessionListParams
	}
	mock.lockV2SessionList.RLock()
	calls = mock.calls.V2SessionList
	mock.lockV2SessionList.RUnlock()
	return calls
}

// V2SessionMessages calls V2SessionMessagesFunc.
func (mock *HandlerMock) V2SessionMessages(ctx context.Context, params opencodeapi.V2SessionMessagesParams) (opencodeapi.V2SessionMessagesRes, error) {
	if mock.V2SessionMessagesFunc == nil {
		panic("HandlerMock.V2SessionMessagesFunc: method is nil but Handler.V2SessionMessages was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params opencodeapi.V2SessionMessagesParams
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockV2SessionMessages.Lock()
	mock.calls.V2SessionMessages = append(mock.calls.V2SessionMessages, callInfo)
	mock.lockV2SessionMessages.Unlock()
	return mock.V2SessionMessagesFunc(ctx, params)
}

// V2SessionMessagesCalls gets all the calls that were made to V2SessionMessages.
// Check the length with:
//
//	len(mockedHandler.V2SessionMessagesCalls())
func (mock *HandlerMock) V2SessionMessagesCalls() []struct {
	Ctx    context.Context
	Params opencodeapi.V2SessionMessagesParams
} {
	var calls []struct {
		Ctx    context.Context
		Params opencodeapi.V2SessionMessagesParams
	}
	mock.lockV2SessionMessages.RLock()
	calls = mock.calls.V2SessionMessages
	mock.lockV2SessionMessages.RUnlock()
	return calls
}

// V2SessionPermissionList calls V2SessionPermissionListFunc.
func (mock *HandlerMock) V2SessionPermissionList(ctx context.Context, params opencodeapi.V2SessionPermissionListParams) (opencodeapi.V2SessionPermissionListRes, error) {
	if mock.V2SessionPermissionListFunc == nil {
		panic("HandlerMock.V2SessionPermissionListFunc: method is nil but Handler.V2SessionPermissionList was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params opencodeapi.V2SessionPermissionListParams
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockV2SessionPermissionList.Lock()
	mock.calls.V2SessionPermissionList = append(mock.calls.V2SessionPermissionList, callInfo)
	mock.lockV2SessionPermissionList.Unlock()
	return mock.V2SessionPermissionListFunc(ctx, params)
}

// V2SessionPermissionListCalls gets all the calls that were made to V2SessionPermissionList.
// Check the length with:
//
//	len(mockedHandler.V2SessionPermissionListCalls())
func (mock *HandlerMock) V2SessionPermissionListCalls() []struct {
	Ctx    context.Context
	Params opencodeapi.V2SessionPermissionListParams
} {
	var calls []struct {
		Ctx    context.Context
		Params opencodeapi.V2SessionPermissionListParams
	}
	mock.lockV2SessionPermissionList.RLock()
	calls = mock.calls.V2SessionPermissionList
	mock.lockV2SessionPermissionList.RUnlock()
	return calls
}

// V2SessionPermissionReply calls V2SessionPermissionReplyFunc.
func (mock *HandlerMock) V2SessionPermissionReply(ctx context.Context, req *opencodeapi.V2SessionPermissionReplyReq, params opencodeapi.V2SessionPermissionReplyParams) (opencodeapi.V2SessionPermissionReplyRes, error) {
	if mock.V2SessionPermissionReplyFunc == nil {
		panic("HandlerMock.V2SessionPermissionReplyFunc: method is nil but Handler.V2SessionPermissionReply was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Req    *opencodeapi.V2SessionPermissionReplyReq
		Params opencodeapi.V2SessionPermissionReplyParams
	}{
		Ctx:    ctx,
		Req:    req,
		Params: params,
	}
	mock.lockV2SessionPermissionReply.Lock()
	mock.calls.V2SessionPermissionReply = append(mock.calls.V2SessionPermissionReply, callInfo)
	mock.lockV2SessionPermissionReply.Unlock()
	return mock.V2SessionPermissionReplyFunc(ctx, req, params)
}

// V2SessionPermissionReplyCalls gets all the calls that were made to V2SessionPermissionReply.
// Check the length with:
//
//	len(mockedHandler.V2SessionPermissionReplyCalls())
func (mock *HandlerMock) V2SessionPermissionReplyCalls() []struct {
	Ctx    context.Context
	Req    *opencodeapi.V2SessionPermissionReplyReq
	Params opencodeapi.V2SessionPermissionReplyParams
} {
	var calls []struct {
		Ctx    context.Context
		Req    *opencodeapi.V2SessionPermissionReplyReq
		Params opencodeapi.V2SessionPermissionReplyParams
	}
	mock.lockV2SessionPermissionReply.RLock()
	calls = mock.calls.V2SessionPermissionReply
	mock.lockV2SessionPermissionReply.RUnlock()
	return calls
}

// V2SessionPrompt calls V2SessionPromptFunc.
func (mock *HandlerMock) V2SessionPrompt(ctx context.Context, req *opencodeapi.V2SessionPromptReq, params opencodeapi.V2SessionPromptParams) (opencodeapi.V2SessionPromptRes, error) {
	if mock.V2SessionPromptFunc == nil {
		panic("HandlerMock.V2SessionPromptFunc: method is nil but Handler.V2SessionPrompt was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Req    *opencodeapi.V2SessionPromptReq
		Params opencodeapi.V2SessionPromptParams
	}{
		Ctx:    ctx,
		Req:    req,
		Params: params,
	}
	mock.lockV2SessionPrompt.Lock()
	mock.calls.V2SessionPrompt = append(mock.calls.V2SessionPrompt, callInfo)
	mock.lockV2SessionPrompt.Unlock()
	return mock.V2SessionPromptFunc(ctx, req, params)
}

// V2SessionPromptCalls gets all the calls that were made to V2SessionPrompt.
// Check the length with:
//
//	len(mockedHandler.V2SessionPromptCalls())
func (mock *HandlerMock) V2SessionPromptCalls() []struct {
	Ctx    context.Context
	Req    *opencodeapi.V2SessionPromptReq
	Params opencodeapi.V2SessionPromptParams
} {
	var calls []struct {
		Ctx    context.Context
		Req    *opencodeapi.V2SessionPromptReq
		Params opencodeapi.V2SessionPromptParams
	}
	mock.lockV2SessionPrompt.RLock()
	calls = mock.calls.V2SessionPrompt
	mock.lockV2SessionPrompt.RUnlock()
	return calls
}

// V2SessionQuestionReject calls V2SessionQuestionRejectFunc.
func (mock *HandlerMock) V2SessionQuestionReject(ctx context.Context, params opencodeapi.V2SessionQuestionRejectParams) (opencodeapi.V2SessionQuestionRejectRes, error) {
	if mock.V2SessionQuestionRejectFunc == nil {
		panic("HandlerMock.V2SessionQuestionRejectFunc: method is nil but Handler.V2SessionQuestionReject was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params opencodeapi.V2SessionQuestionRejectParams
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockV2SessionQuestionReject.Lock()
	mock.calls.V2SessionQuestionReject = append(mock.calls.V2SessionQuestionReject, callInfo)
	mock.lockV2SessionQuestionReject.Unlock()
	return mock.V2SessionQuestionRejectFunc(ctx, params)
}

// V2SessionQuestionRejectCalls gets all the calls that were made to V2SessionQuestionReject.
// Check the length with:
//
//	len(mockedHandler.V2SessionQuestionRejectCalls())
func (mock *HandlerMock) V2SessionQuestionRejectCalls() []struct {
	Ctx    context.Context
	Params opencodeapi.V2SessionQuestionRejectParams
} {
	var calls []struct {
		Ctx    context.Context
		Params opencodeapi.V2SessionQuestionRejectParams
	}
	mock.lockV2SessionQuestionReject.RLock()
	calls = mock.calls.V2SessionQuestionReject
	mock.lockV2SessionQuestionReject.RUnlock()
	return calls
}

// V2SessionQuestionReply calls V2SessionQuestionReplyFunc.
func (mock *HandlerMock) V2SessionQuestionReply(ctx context.Context, req *opencodeapi.QuestionV2Reply, params opencodeapi.V2SessionQuestionReplyParams) (opencodeapi.V2SessionQuestionReplyRes, error) {
	if mock.V2SessionQuestionReplyFunc == nil {
		panic("HandlerMock.V2SessionQuestionReplyFunc: method is nil but Handler.V2SessionQuestionReply was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Req    *opencodeapi.QuestionV2Reply
		Params opencodeapi.V2SessionQuestionReplyParams
	}{
		Ctx:    ctx,
		Req:    req,
		Params: params,
	}
	mock.lockV2SessionQuestionReply.Lock()
	mock.calls.V2SessionQuestionReply = append(mock.calls.V2SessionQuestionReply, callInfo)
	mock.lockV2SessionQuestionReply.Unlock()
	return mock.V2SessionQuestionReplyFunc(ctx, req, params)
}

// V2SessionQuestionReplyCalls gets all the calls that were made to V2SessionQuestionReply.
// Check the length with:
//
//	len(mockedHandler.V2SessionQuestionReplyCalls())
func (mock *HandlerMock) V2SessionQuestionReplyCalls() []struct {
	Ctx    context.Context
	Req    *opencodeapi.QuestionV2Reply
	Params opencodeapi.V2SessionQuestionReplyParams
} {
	var calls []struct {
		Ctx    context.Context
		Req    *opencodeapi.QuestionV2Reply
		Params opencodeapi.V2SessionQuestionReplyParams
	}
	mock.lockV2SessionQuestionReply.RLock()
	calls = mock.calls.V2SessionQuestionReply
	mock.lockV2SessionQuestionReply.RUnlock()
	return calls
}

// V2SessionWait calls V2SessionWaitFunc.
func (mock *HandlerMock) V2SessionWait(ctx context.Context, params opencodeapi.V2SessionWaitParams) (opencodeapi.V2SessionWaitRes, error) {
	if mock.V2SessionWaitFunc == nil {
		panic("HandlerMock.V2SessionWaitFunc: method is nil but Handler.V2SessionWait was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params opencodeapi.V2SessionWaitParams
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockV2SessionWait.Lock()
	mock.calls.V2SessionWait = append(mock.calls.V2SessionWait, callInfo)
	mock.lockV2SessionWait.Unlock()
	return mock.V2SessionWaitFunc(ctx, params)
}

// V2SessionWaitCalls gets all the calls that were made to V2SessionWait.
// Check the length with:
//
//	len(mockedHandler.V2SessionWaitCalls())
func (mock *HandlerMock) V2SessionWaitCalls() []struct {
	Ctx    context.Context
	Params opencodeapi.V2SessionWaitParams
} {
	var calls []struct {
		Ctx    context.Context
		Params opencodeapi.V2SessionWaitParams
	}
	mock.lockV2SessionWait.RLock()
	calls = mock.calls.V2SessionWait
	mock.lockV2SessionWait.RUnlock()
	return calls
}
